services:

  Craft\Http\Controller\ActionArgumentBuilderInterface: '@craft.http.controller.action_argument_builder'

  Craft\Http\Controller\ActionArgumentBuilder:
    class: Craft\Http\Controller\ActionArgumentBuilder
    arguments:
      - '@craft.data.validation.structured_data_validator'

  # Resolve JSON POST body
  Craft\Http\EventListener\JsonPostDataResolverListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 9999 }

  # Exception response handler
  Craft\Http\EventListener\ExceptionHandlerListener:
    arguments:
      - '@logger'
      - "%craft.env%"
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 250 }

  # Handle request objects building
  Craft\Http\Controller\ActionArgumentResolver:
    arguments:
      - '@logger'
      - '@craft.http.controller.action_argument_builder'
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  # Response output handler
  Craft\Http\EventListener\ResponseHandlerListener:
    arguments:
      - '@logger'
      - "%craft.env%"
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: build, priority: 255 }
