parameters:
  craft.env: '%env(APP_ENV)%'

imports:
  - { resource: data/services.yaml }
  - { resource: messaging/services.yaml }
  - { resource: http/services.yaml }
  - { resource: security/services.yaml }
