parameters:
  craft.env: '%env(APP_ENV)%'
services:

  Craft\Security\User\SecurityUserProviderInterface: '@craft.security.user.provider'
  craft.security.user.provider:
    class: Craft\Security\User\SecurityUserProvider
    arguments:
      - '@Craft\Security\Authentication\TokenManagerInterface'
      - '@Craft\Security\Authorization\AuthorizationRegistryInterface'


  Craft\Security\Authentication\TokenAuthenticatorInterface: '@craft.security.authentication.token_authenticator'
  craft.security.authentication.token_authenticator:
    class: Craft\Security\Authentication\TokenAuthenticator
    arguments:
      - '@Craft\Security\User\SecurityUserProviderInterface'
      - '@Craft\Security\User\SecurityUserProviderInterface'


  Craft\Security\Authentication\TokenManagerInterface: '@craft.security.authentication.token_manager'
  craft.security.authentication.token_manager:
    class: Craft\Security\Authentication\TokenManager
    arguments:
      - '%craft.security.key%'
      - '@Psr\Log\LoggerInterface'

  Craft\Security\Authorization\RoutesAuthorizationRegistryInterface: '@craft.security.authorization.routes_registry'
  craft.security.authorization.routes_registry:
    class: Craft\Security\Authorization\RoutesAuthorizationRegistry
    arguments:
      - '@Symfony\Component\Routing\RouterInterface'
      - '@Psr\Log\LoggerInterface'


  # Resolve JSON POST body
  Craft\Http\EventListener\JsonPostDataResolverListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 9999 }

  # Exception response handler
  Craft\Http\EventListener\ExceptionHandlerListener:
    arguments:
      - '@logger'
      - "%craft.env%"
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 250 }

  # Handle request objects building
  Craft\Http\Controller\ActionArgumentResolver:
    arguments: ['@logger', '@security.helper']
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  # Response output handler
  Craft\Http\EventListener\ResponseHandlerListener:
    arguments: ['@logger']
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: build, priority: 255 }

  # Authorization system voter
  Craft\Security\Authorization\RbacAuthorizer:
    arguments:
      - '@security.helper'
      - '@Craft\Security\Authorization\RoutesAuthorizationRegistryInterface'
      - '@Psr\Log\LoggerInterface'
    tags:
      - { name: security.voter }
